	</main>
	
	<footer class="site-footer">
	    <nav>
			<a href="<?= $config['base_path'] ?>/rss/">RSS</a> 
			<a href="<?= $config['base_path'] ?>/json/">JSON</a>
	    </nav>
	    <p>
		    Powered by <a href="https://nicholas.adgr.dev/">Nicholas</a> ✨
		</p>
	</footer>
</body>
</html>
<?php
global $start_time;
$end_time = microtime(true);
$time_taken = number_format(($end_time - $start_time) * 1000, 2); // Convert to milliseconds and format to 2 decimal places

if($config['use_frontend']) {
	echo '<!-- Generated by Nicholas in ' . $time_taken . 'ms ✨ -->';
}